### ISSUE TITLE
Viewed Command Output Wrong

### ISSUE THREAD

**Issue by DeadSkull1205** [navi1995/Movie-Night-Discord-Bot#20]
While giving the viewed command the bot outputs Messages "**List of unviewed movies is currently empty.**". Can u please correct it.
![Screenshot 2021-03-21 201336](https://user-images.githubusercontent.com/66433377/111909156-266d2200-8a82-11eb-8886-0e5aa50177cb.png)

**Comment by navi1995** [comment]
Fixed in commit https://github.com/navi1995/Movie-Night-Discord-Bot/commit/37b34a196e929d9d133896d3d69001e03992225d 

Will roll this out later today to production. Thanks for reporting!
