### ISSUE TITLE
Bot not counting votes properly

### ISSUE THREAD

**Issue by PetriVukan** [navi1995/Movie-Night-Discord-Bot#21]
The past couple days I've been noticing 2 errors:

1. Wrong vote count in chosen movie embed. (A winner has been chosen! X with 1 votes.) The count is often wrong.
2. The bot choosing the wrong movie, while there is a clear winner. The bot somehow doesn't choose the movie with the most votes.

**Comment by PetriVukan** [comment]
Example:
![afbeelding](https://user-images.githubusercontent.com/7229530/112218947-a92de280-8c24-11eb-849c-02051ae3c70e.png)
![afbeelding](https://user-images.githubusercontent.com/7229530/112218969-ad5a0000-8c24-11eb-91d6-07c4e953df2a.png)

**Comment by navi1995** [comment]
Hi @PetriVukan ,

I've pushed out a few code cleanups that should fix these issues. Have you noticed anything recently since the polltime has been reduced?

**Comment by PetriVukan** [comment]
Hi,

I haven't noticed any issues lately. Thanks for the update! I'll keep you posted if I encounter any issues.
