### ISSUE TITLE
Polltime

### ISSUE THREAD

**Issue by Ravedite** [navi1995/Movie-Night-Discord-Bot#22]
We used to be able to set polltime to 86399 seconds (just shy of one day) and as of today the bot wont let us. Not only that, but when trying to set the "default" 7200 seconds, it still won't let us and after checking the deafult polltime seems to be 3600 seconds despite the message.
![image](https://user-images.githubusercontent.com/27501259/114104409-78f86c00-98d3-11eb-8fe4-6fa473fc5fd3.png)

**Comment by navi1995** [comment]
Hey there, unfortunately setting the polltime limit to a day was leading to a tonne of server instability and crashes which meant the server or bot would have to restart, and a lot of polls would be cancelled. I'm currently experimenting to fine tune the max to a value that will also be stable. 

I've pushed out a fix for the above messages, currently the max is 2 hours now but may be increased or decreased in a few days depending on stability.
