### ISSUE TITLE
Bot offline on new server.

### ISSUE THREAD

**Issue by DashieLashie** [navi1995/Movie-Night-Discord-Bot#51]
I manage two server, one new and one old. On the old one the bot works as intended but on the new server the bot appears offline and nothing has worked to get it to respond. I'm I doing something wrong?

**Comment by Kodaijin** [comment]
Same here but over all 4 servers I have the bot on it is showing offline. I'm guessing it just needs to be reset on the host end (where ever it is). 

If it dose not come back up I might just do a pull and host it my self.
