### ISSUE TITLE
Bot does not respond to commands

### ISSUE THREAD

**Issue by covertskippy55** [navi1995/Movie-Night-Discord-Bot#64]
Hello, bot was working fine until a week ago or so. No longer responding to -- commands. Thanks

**Comment by navi1995** [comment]
Hi there,The bots been upgraded to use slash commands as discord will be ending support for prefix commands on the 31st of august. Go ahead and type / in discord and you should see a bunch of movie night bot commands. On 25 Aug 2022 18:55, Dilan ***@***.***> wrote:
Hello, bot was working fine until a week ago or so. No longer responding to -- commands. Thanks

**Comment by covertskippy55** [comment]
Oh good to know, thanks!
