### ISSUE TITLE
Poll size is always 5

### ISSUE THREAD

**Issue by derekdavis2013** [navi1995/Movie-Night-Discord-Bot#66]
When creating a poll, the size parameter seems to be getting ignored. Five movies from the list are always returned.

**Comment by derekdavis2013** [comment]
I think the bug is caused by this line of code:
https://github.com/navi1995/Movie-Night-Discord-Bot/blob/master/Discord%20Bot/commands/poll.js#L19

`const pollSize` is looking at `interaction.options.getInteger("seconds")`

**Comment by navi1995** [comment]
Great catch, good ol' copy paste hits again. Thanks for the PR! I'll deploy the changes now.
