### ISSUE TITLE
Not all users can run polls, even with /pollrole is cleared

### ISSUE THREAD

**Issue by slegeza** [navi1995/Movie-Night-Discord-Bot#69]
Recently, I ran the following command on my Discord server: 

![image](https://user-images.githubusercontent.com/25915078/188250520-c39ce0e6-58e4-4124-bb96-7e649e6e4970.png)

But, users are still unable to run polls, unless they are the server administrator: 

![image](https://user-images.githubusercontent.com/25915078/188250474-f488c44c-8293-4bf4-9044-126cc97065c4.png)

**Comment by navi1995** [comment]
@slegeza Thanks for letting me know! Sorry been overseas and will be for a bit but I'll try and have a look when I can

**Comment by navi1995** [comment]
@slegeza I've just pushed out an update and should fix this issue. Could you try it out and let me know? If good let me know and I'll close the issue

**Comment by slegeza** [comment]
> 

This appears to have been fixed! Thanks for this!!!
