### ISSUE TITLE
Suggestion: Add slash command to manually trigger Watched Status

### ISSUE THREAD

**Issue by volrathism** [navi1995/Movie-Night-Discord-Bot#79]
Being able to manually mark a movie watched or unwatched would be very useful in case of canceled movie nights and/or mistakes made.

**Comment by navi1995** [comment]
The /toggleviewed command will do this for you :) On Dec 19, 2022 16:10, volrathism ***@***.***> wrote:
Being able to manually mark a movie watched or unwatched would be very useful in case of canceled movie nights and/or mistakes made.

**Comment by volrathism** [comment]
Oh ok. I didn't see that command anywhere in the lists on the site or in Discord.
