### ISSUE TITLE
Bot shows as Offline for a Week

### ISSUE THREAD

**Issue by volrathism** [navi1995/Movie-Night-Discord-Bot#81]
The bot has been offline for a week. I tried re-inviting , but that didn't help. I've even kicked it and invited it again just to make sure.

**Comment by VoidCross** [comment]
Same issue on my end, something for sure wrong with the bot.

**Comment by navi1995** [comment]
Apologies folks, was on holiday and the server I run it on had gone down. This happens from time to time when billing falls through
